### ISSUE TITLE
SPTAudioStreamingController setTrackListPosition causes EXC_BAC_ACCESS crashes

### ISSUE THREAD

**Issue by andreassylvester** [spotify/ios-sdk#172]
Ever since SDK 5 changing tracks has been causing unrecoverable crashes in my app. 
Have tried swapping setTrackListPosition out in favor of skipNext/skipPrev but the crashes keep happening. Would greatly appreciate any insight as to why this is happening. :pray: 

Full stack trace:
—0	0x0000000100144704 in sp_fb0c70531a7f4bafab8176502af9711a ()
—1	0x000000010013cfd4 in sp_6cc1928338054ead9d26204cce33208c ()
—2	0x000000010012f160 in sp_a5a9885692d84284afb957bab702828b ()
—3	0x000000010012f948 in sp_d9d0ca2d567944e9814b38032b0ec24b ()
—4	0x000000010013a1e8 in sp_246ae1468219490d9a66acd0037692ff ()
—5	0x0000000100141e04 in sp_08cd5180078b497d81deabeac68dc2db ()
—6	0x000000010013f458 in SpPumpEvents ()
 —7	0x000000010010b868 in audioTimerFired at /Users/spotify-buildagent/buildAgent/work/f0512cb09316daec/src/__SPTAudioStreamingController.m:1158__:scream:
—8	0x0000000183426210 in \_\_CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION\_\_ ()
—9	0x0000000183425ec0 in \_\_CFRunLoopDoTimer ()
—10	0x000000018342390c in \_\_CFRunLoopRun ()
—11	0x0000000183351664 in CFRunLoopRunSpecific ()
—12	0x00000001833a371c in CFRunLoopRun ()
—13	0x000000010010be10 in +[SPTAudioStreamingController runBackgroundRunloop:] at /Users/spotify-buildagent/buildAgent/work/f0512cb09316daec/src/__SPTAudioStreamingController.m:1272__:scream:
—14	0x000000018433a60c in \_\_NSThread\_\_main\_\_ ()
—15	0x0000000194277e80 in _pthread_body ()
—16	0x0000000194277ddc in _pthread_start ()

**Comment by possan** [comment]
Have you found any solution to this?

**Comment by andreassylvester** [comment]
Since I have no insight in as to what happens at those specific code points, no I haven't found any solution. I spent quite a bit of time modyfing my code in ways that I guessed might alter this behaviour but it has persisted throughout.

**Comment by mattga** [comment]
I am experiencing the same crashes with the same stack trace:

#0	0x31e7b6ba in objc_retain ()
#1	0x0013ba00 in cb_on_audio_data at /Users/po/Projects/ios-sdk/src/SPTAudioStreamingController.m:978
#2	0x00170cea in sp_6c0dcd56b5b440298237fba70b491c2e ()
#3	0x0015ef96 in sp_b6b618e30cd54da6b4b741fd77e5dd09 ()
#4	0x0015df24 in sp_e3ab6c5e4152442eaa298e8c47bf29b9 ()
#5	0x0015ddba in sp_9b8a108c9e6e4804ab80faaa543a2346 ()
#6	0x0015e71e in sp_b8988266b5d84875bcf01e1c60027f93 ()
#7	0x00168fa6 in sp_b338f80c4632468a8bc0171b11d8c1df ()
#8	0x0017174a in sp_c5f8823ef3534361980fe59611600175 ()
#9	0x0016ec9c in SpPumpEvents ()
#10	0x0013f0b0 in audioTimerFired at /Users/po/Projects/ios-sdk/src/SPTAudioStreamingController.m:1005
#11	0x24648c86 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ ()
#12	0x24648802 in __CFRunLoopDoTimer ()
#13	0x24646a52 in __CFRunLoopRun ()
#14	0x245943c0 in CFRunLoopRunSpecific ()
#15	0x245dd0ea in CFRunLoopRun ()
#16	0x0013f4f2 in +[SPTAudioStreamingController runBackgroundRunloop:] at /Users/po/Projects/ios-sdk/src/SPTAudioStreamingController.m:1096
#17	0x25392b5a in __NSThread__main__ ()
#18	0x32524e92 in _pthread_body ()
#19	0x32524e06 in _pthread_start ()

Have yet to attribute the crash to any action or behavior of the app...

**Comment by possan** [comment]
We just sent out a new version, which should fix this issue, it would be great if you could confirm that it's fixed.

**Comment by mattga** [comment]
Will do. Thanks for letting me know.

On Wednesday, March 4, 2015, Per-Olov Jernberg <notifications@github.com>
wrote:

> We just sent out a new version, which should fix this issue, it would be
> great if you could confirm that it's fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/ios-sdk/issues/172#issuecomment-77203356>.
>


-- 
Regards,
Matthew Gardner

**Comment by capsulefm** [comment]
I'm still getting a crash in SpPumpEvents on SDK7:

    libobjc.A.dylib 0x32437f56 objc_msgSend + 22
    1	capsule.fm 0x004bb3cb sp_a19a410b3a62469ea4fb375e82e42247 + 2124
    2	capsule.fm 0x004b744d sp_72d5b904b9f54c22ab21145a2b0b6ea2 + 786
    3	capsule.fm 0x004b64cf sp_265ac87642b744c7a39d6224bed3a2aa + 296
    4	capsule.fm 0x004bc037 sp_a9aca864c0274c96b7edb95d65279798 + 48
    5	capsule.fm 0x004b9dd5 SpPumpEvents + 94
    6	CoreFoundation 0x2413fedf __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 12
    7	CoreFoundation 0x2413fa5b __CFRunLoopDoTimer + 648
    8	CoreFoundation 0x2413dcab __CFRunLoopRun + 1416
    9	CoreFoundation 0x2408a201 CFRunLoopRunSpecific + 474
    10	CoreFoundation 0x240d2f23 CFRunLoopRun + 96
    11	capsule.fm 0x0048ce8f +[SPTAudioStreamingController runBackgroundRunloop:](SPTAudioStreamingController.m:1441)
    12	Foundation 0x24eb83bb __NSThread__main__ + 1116
    13	libsystem_pthread.dylib 0x32affe23 _pthread_body + 136
    14	libsystem_pthread.dylib 0x32affd97 _pthread_start + 116
    15	libsystem_pthread.dylib 0x32afdb20 thread_start + 6`
