### ISSUE TITLE
Playback (current position) returns to 0.0 at end of track, even when there is no next track/queue

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#319]
Currently, when playing a single track, playback returns to 0.0 once the track ends. Playback instead should stop at the end of the track (like the default behavior of AVPlayer, and most audio controllers in general) or at least provide an option for the behavior.

**Comment by mhuusko5** [comment]
Is there a status on this? With the current behaviour it's not possible to tell the difference between a track that ended playing, or one that just started but is paused at 0.0.

**Comment by DmytroAnkudinov** [comment]
Issue has been fixed as of beta24 and does not occur again.

**Comment by mhuusko5** [comment]
This is still happening as of Beta 25. When a track ends, the player resets to position 0.0 (even before/by the time `didStopPlayingTrack:` gets called).
